# -*- coding: utf-8 -*-
"""6320 Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yu8cUG7owhnqMrIyo1LMdtQLbCSic5Sc
"""

!pip install openai

import pandas as pd

df = pd.read_csv("fraud_email_.csv")
print(df.head())

dataset = df.sample(n=25, random_state=42).reset_index(drop=True)

print(dataset.head())

from openai import OpenAI
import openai
import os

openai.api_key = ""

client = OpenAI(api_key=openai.api_key)

def classify_email(text):
    prompt = f"Decide whether the following email is spam or not spam:\n\nEmail: \"{text}\"\n\nAnswer only with '1' for spam or '0' for not spam."

    response = client.chat.completions.create(
        model="gpt-3.5-turbo",
        messages=[{"role": "user", "content": prompt}],
        temperature=0
    )

    return response.choices[0].message.content.strip().lower()

TP = FP = TN = FN = 0

for _, row in dataset.iterrows():
    prediction = classify_email(row['Text'])
    label = row['Class']

    print(prediction, " ", label)
    if prediction == "1":
        if label == 1:
            TP += 1
        else:
            FP += 1
    else:
        if label == 0:
            TN += 1
        else:
            FN += 1

print(f"TP: {TP}, FP: {FP}, TN: {TN}, FN: {FN}")

