# -*- coding: utf-8 -*-
"""bert_scam_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18SSWvBn4y5GrSIrF0wAgo60HIc3jdXwf
"""

import tensorflow as tf
from transformers import BertTokenizer, TFBertForSequenceClassification
import numpy as np
import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from sklearn.model_selection import train_test_split
import csv
import random

nltk.download('stopwords')
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
max_len = 512
df = pd.read_csv('spam.csv', encoding='latin-1')

def clean_email_body(text):
    if not text is str:
      text = str(text)
    text = text.lower()
    text = re.sub(r'<.*?>', '<HTML>', text)
    text = re.sub(r'http\S+|www\S+|https\S+', '<URL>', text)
    text = re.sub(r'\S+@\S+', '<EMAIL>', text)
    text = re.sub(r'[^a-z\s]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    stop_words = set(stopwords.words('english'))
    text = ' '.join([word for word in text.split() if word not in stop_words])
    ps = PorterStemmer()
    text = ' '.join([ps.stem(word) for word in text.split()])
    return text

def predict_email(text): # get probability of scam
    cleaned_text = clean_email_body(text)
    inputs = tokenizer(
        cleaned_text,
        max_length=max_len,
        padding='max_length',
        truncation=True,
        return_tensors='tf'
    )
    outputs = model(inputs)
    logit = outputs.logits[0][0].numpy()
    prob = tf.sigmoid(logit).numpy()
    label = 1 if prob >= 0.5 else 0
    label_map = {0: 'not scam', 1: 'scam'}
    return float(prob)

def test_case(email: str, scam: str):
    claude_scam = predict_email(email)
    if claude_scam >= 0.5:
        claude_scam = '1'
    else:
        claude_scam = '0'

    if scam == 'spam':
        scam = '1'
    else:
        scam = '0'
    TP = 0
    TN = 0
    FP = 0
    FN = 0

    if scam == claude_scam:
        if scam == '1':
            TP += 1
        else:
            TN += 1
    elif scam == '0' and claude_scam == '1':
        FP += 1
    elif scam == '1' and claude_scam == '0':
        FN += 1
    else:
        print(f"a row was skipped due to formatting problems. scam = {scam} and claude_scam = {claude_scam}")
    return TP, TN, FP, FN

model = tf.keras.models.load_model('bert_spam_dataset_model', custom_objects={'TFBertForSequenceClassification': TFBertForSequenceClassification})

with(open("spam.csv", mode="r", encoding='latin-1')) as test_data:
    df['v2'] = df['v2'].apply(clean_email_body)
    df['v1'] = df['v1'].map({'spam': 1, 'ham': 0})
    reader = csv.reader(test_data)
    next(reader)
    rows = list(reader)
    test_rows = random.sample(rows, 100)
    TP, TN, FP, FN = 0, 0, 0, 0
    for row in test_rows:
        email = row[1]
        scam = row[0]
        TP_new, TN_new, FP_new, FN_new = test_case(email, scam)
        TP += TP_new
        TN += TN_new
        FP += FP_new
        FN += FN_new
    print(f"TP={TP}, TN={TN}, FP={FP}, FN={FN}")
